spring.datasource.url=jdbc:h2:file:./data/sekai_friend;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

server.port=8089
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8
server.tomcat.connection-timeout=600000
server.tomcat.max-http-form-post-size=4200MB

spring.servlet.multipart.max-file-size=4096MB
spring.servlet.multipart.max-request-size=4200MB

mybatis.mapper-locations=classpath*:com.sekai.sekai_form.mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

server.servlet.session.timeout=120m
server.servlet.session.cookie.max-age=7200
server.servlet.session.cookie.name=JSESSIONID_M9
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8